[toolchain]
channel = "nightly-2023-03-25"
targets = [
    "aarch64-apple-darwin",
    "aarch64-linux-android",
    "aarch64-unknown-linux-gnu",
    "wasm32-unknown-unknown",
    "x86_64-unknown-linux-gnu",
]
